### ISSUE TITLE
Error on login

### ISSUE THREAD

**Issue by franklupo** [sAleksovski/scrum-board-frontend#1]
Hi,

after login recive message 

> Error: connect ECONNREFUSED 127.0.0.1:8080
>    at Object.exports._errnoException (util.js:870:11)
>    at exports._exceptionWithHostPort (util.js:893:20)
>    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1061:14)

Tanks

**Comment by sAleksovski** [comment]
You will need the [backend](https://github.com/sAleksovski/scrum-board) running on port 8080.
