### ISSUE TITLE
Uncaught Error: [$injector:unpr] Unknown provider: $$isDocumentHiddenProvider <- $$isDocumentHidden <- $$animateQueue <- $animate <- $compile <- $$animateQueue

### ISSUE THREAD

**Issue by mesutcakir** [sAleksovski/scrum-board-frontend#2]
![image](https://cloud.githubusercontent.com/assets/4125460/21041532/4792144a-bdf4-11e6-93fa-4c6463c86bd7.png)

Uncaught Error: [$injector:unpr] Unknown provider: $$isDocumentHiddenProvider <- $$isDocumentHidden <- $$animateQueue <- $animate <- $compile <- $$animateQueue
http://errors.angularjs.org/1.5.9/$injector/unpr?p0=%24%24isDocumentHiddenP…eQueue%20%3C-%20%24animate%20%3C-%20%24compile%20%3C-%20%24%24animateQueue
    at lib.js?rev=641c7a7…:68
    at lib.js?rev=641c7a7…:4554
    at Object.getService [as get] (lib.js?rev=641c7a7…:4707)
    at lib.js?rev=641c7a7…:4559
    at getService (lib.js?rev=641c7a7…:4707)
    at injectionArgs (lib.js?rev=641c7a7…:4732)
    at Object.invoke (lib.js?rev=641c7a7…:4754)
    at lib.js?rev=641c7a7…:4560
    at getService (lib.js?rev=641c7a7…:4707)
    at injectionArgs (lib.js?rev=641c7a7…:4732)

**Comment by sAleksovski** [comment]
Thanks.

I think the problem was that the angular and angular-animate version was different, and it was causing some issues.
I've set the version to 1.5.3, the one I know works because that's what I have locally.

You can try again now.

**Comment by mesutcakir** [comment]
Yes, 1.6.x has improved transitions.
